# Generated by Django 2.2.12 on 2020-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_one', models.CharField(max_length=255)),
                ('skill_two', models.CharField(max_length=255)),
                ('skill_three', models.CharField(max_length=255)),
                ('skill_ultimate', models.CharField(max_length=255)),
                ('skill_passive', models.CharField(max_length=255)),
                ('hidden_skill_potential', models.CharField(max_length=255)),
            ],
        ),
    ]
