# Generated by Django 2.2.12 on 2020-09-04 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenSkillPotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(800)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPassive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(300)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillUlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_damage', models.FloatField(validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(500)])),
                ('skill_effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SkillLibrary',
        ),
    ]
