# Generated by Django 2.2.12 on 2020-09-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0002_auto_20200904_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_skill_potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.HiddenSkillPotential')),
                ('skill_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.SkillOne')),
                ('skill_passive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.SkillPassive')),
                ('skill_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.SkillThree')),
                ('skill_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.SkillTwo')),
                ('skill_ult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvp.SkillUlt')),
            ],
        ),
    ]
