# Generated by Django 2.2.12 on 2020-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0003_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenskillpotential',
            name='skill_damage',
            field=models.FloatField(default=708),
        ),
        migrations.AlterField(
            model_name='skillone',
            name='skill_damage',
            field=models.FloatField(default=99),
        ),
        migrations.AlterField(
            model_name='skillpassive',
            name='skill_damage',
            field=models.FloatField(default=97),
        ),
        migrations.AlterField(
            model_name='skillthree',
            name='skill_damage',
            field=models.FloatField(default=119),
        ),
        migrations.AlterField(
            model_name='skilltwo',
            name='skill_damage',
            field=models.FloatField(default=182),
        ),
        migrations.AlterField(
            model_name='skillult',
            name='skill_damage',
            field=models.FloatField(default=488),
        ),
    ]
