# Generated by Django 2.2.12 on 2020-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0004_auto_20200904_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenskillpotential',
            name='skill_damage',
            field=models.FloatField(default=460, unique=True),
        ),
        migrations.AlterField(
            model_name='skillone',
            name='skill_damage',
            field=models.FloatField(default=61, unique=True),
        ),
        migrations.AlterField(
            model_name='skillpassive',
            name='skill_damage',
            field=models.FloatField(default=64, unique=True),
        ),
        migrations.AlterField(
            model_name='skillthree',
            name='skill_damage',
            field=models.FloatField(default=158, unique=True),
        ),
        migrations.AlterField(
            model_name='skilltwo',
            name='skill_damage',
            field=models.FloatField(default=173, unique=True),
        ),
        migrations.AlterField(
            model_name='skillult',
            name='skill_damage',
            field=models.FloatField(default=403, unique=True),
        ),
    ]
