# Generated by Django 2.2.12 on 2020-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0006_auto_20200904_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenskillpotential',
            name='skill_damage',
            field=models.FloatField(default=350),
        ),
        migrations.AlterField(
            model_name='skillone',
            name='skill_damage',
            field=models.FloatField(default=95),
        ),
        migrations.AlterField(
            model_name='skillpassive',
            name='skill_damage',
            field=models.FloatField(default=58),
        ),
        migrations.AlterField(
            model_name='skillthree',
            name='skill_damage',
            field=models.FloatField(default=119),
        ),
        migrations.AlterField(
            model_name='skilltwo',
            name='skill_damage',
            field=models.FloatField(default=83),
        ),
        migrations.AlterField(
            model_name='skillult',
            name='skill_damage',
            field=models.FloatField(default=302),
        ),
    ]
